name: Deploy Glue Job

on:
  push:
    paths:
      - 'scripts/glue.py'
      - '.github/workflows/deploy_glue.yml'

jobs:
  deploy-glue-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Upload glue.py to S3
      run: aws s3 sync scripts s3://finalyelp/glue-scripts --acl private

    - name: Start Glue Job
      run: aws glue start-job-run --job-name yelpdata
