name: Deploy Glue Job

on:
  push:
    paths:
      - 'scripts/glue.py'   # Trigger only when glue.py changes
      - '.github/workflows/deploy_glue.yml'

jobs:
  deploy-glue-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload glue.py to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl bucket-owner-full-control
      env:
        AWS_S3_BUCKET: finalyelp
        AWS_REGION: us-east-1
        SOURCE_DIR: scripts
        DEST_DIR: yelpraw
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Start Glue Job
      run: |
        aws glue start-job-run --job-name yelpdata --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
