name: Terraform + ETL Automation
on:
  push:
    branches:
      - feature/karan

jobs:
  infra-etl:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials from GitHub secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 # matches variables.tf

      # Step 3: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform -chdir=terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

      # Step 7: Upload ETL script to S3 bucket
      - name: Upload ETL Script to S3
        run: |
          aws s3 cp scripts/etl.py s3://finalyelp2012310/scripts/glue_job.py
          echo "ETL script uploaded to S3."

      # Step 8: Start AWS Glue ETL job
      - name: Start Glue ETL Job
        id: start_etl
        run: |
          JOB_RUN_ID=$(aws glue start-job-run --job-name yelpdata1 --query 'JobRunId' --output text)
          echo "ETL JobRunId: $JOB_RUN_ID"
          echo "job_run_id=$JOB_RUN_ID" >> $GITHUB_OUTPUT

      # Step 9: Wait for ETL job to complete
      - name: Wait for ETL Job Completion
        run: |
          JOB_RUN_ID=${{ steps.start_etl.outputs.job_run_id }}
          while true; do
            STATUS=$(aws glue get-job-run --job-name yelpdata1 --run-id "$JOB_RUN_ID" --query 'JobRun.JobRunState' --output text)
            echo "Current ETL job status: $STATUS"
            if [ "$STATUS" == "SUCCEEDED" ]; then
              echo "ETL Job completed successfully."
              break
            elif [ "$STATUS" == "FAILED" ] || [ "$STATUS" == "STOPPED" ]; then
              echo "ETL Job failed or stopped."
              exit 1
            fi
            sleep 30
          done

      # Step 10: Start AWS Glue crawler
      - name: Start Glue Crawler
        run: aws glue start-crawler --name yelpcrawlers12
