name: Deploy AWS Glue Job
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Script to S3 (Optional)
        run: |
          aws s3 cp glue_job.py s3://your-glue-scripts-bucket/glue_job.py

      - name: Deploy Glue Job
        run: |
          aws glue create-job \
            --name "yelp-data-processing" \
            --role "arn:aws:iam::YOUR_ACCOUNT_ID:role/GlueRole" \
            --command '{"Name": "glueetl", "ScriptLocation": "s3://your-glue-scripts-bucket/glue_job.py"}' \
            --glue-version "3.0" \
            --number-of-workers 2 \
            --worker-type "G.1X"
